### ISSUE TITLE
Failed to build in alpine 3.5, tarantool 1.8

### ISSUE THREAD

**Issue by racktear** [tarantool/memcached#38]
```
In file included from /rocks/memcached/memcached/internal/msgpuck.c:34:0:
/usr/include/msgpuck.h:127:2: error: #error MP_SOURCE is not supported anymore, please link libmsgpuck.a
 #error MP_SOURCE is not supported anymore, please link libmsgpuck.a
```
